name: Benches

on:
  push:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - "examples/**"
  pull_request:
    branches: [ master ]
    paths-ignore:
      - "**.md"
      - "examples/**"

defaults:
  run:
    working-directory: ./benches

jobs:
  clippy-fmt:
    name: "Benches: Check Clippy and rustfmt"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Rustfmt
        run: cargo fmt -- --check
      - name: Clippy
        run: cargo clippy --all-targets -- -D warnings
  benches:
    name: "Benches: Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - name: Test
        run: RUSTFLAGS=-Dwarnings cargo test --benches
