name: gh-pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: GH-pages documentation
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://rust-random.github.io/rand/

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly

      - name: Build docs
        env:
          RUSTDOCFLAGS: --cfg doc_cfg
        # --all builds all crates, but with default features for other crates (okay in this case)
        run: |
          cargo doc --all --all-features --no-deps
          cp utils/redirect.html target/doc/index.html
          rm target/doc/.lock

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './target/doc'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
